pipeline {
  agent none
  parameters {
    booleanParam(name: 'fpgadataflow', defaultValue: true, description: 'Run fpgadataflow tests')
    booleanParam(name: 'sanity', defaultValue: true, description: 'Run sanity hardware and unit tests')
  }
  stages {
    stage('Quicktest') {
      steps {
        sh 'echo "Hello FINN"'
        sh 'hostname'
        sh 'whoami'
        sh 'pwd'
        sh 'docker login'
        sh 'printenv | sort'
        sh './run-docker.sh quicktest'
      }
    }
  }
}
