# Vivado batch flow for MVU add_multi compressor integration test.
# Behavioral simulation — verifies the full mvu_vvu_axi pipeline through the
# DSP lane path (genSoftVec) with add_multi adder trees replaced by generated
# LUT compressor trees via the CATCH_COMP mechanism.
#
# Template placeholders expanded by run_mvu_add_multi_comp_tests.sh:
#   {label}       - Configuration label
#   {mvu_dir}     - Absolute path to finn/finn-rtllib/mvu/
#   {gen_dir}     - Absolute path to gen/<label>/

set label {label}
set tb mvu_add_multi_comp_{label}_tb
set part xcvc1902-vsva2197-2MP-e-S
create_project -force mvu_add_multi_comp_$label mvu_add_multi_comp_$label.vivado -part $part

# Design sources:
#   MVU pipeline:  mvu_pkg.sv, mvu_vvu_axi.sv, replay_buffer.sv,
#                  mvu_vvu_8sx9_dsp58.sv, mvu.sv
#   Patched:       add_multi.sv (with CATCH_COMP entries for this config)
#   Compressors:   comp_*.sv (generated by add_multi_finn.py --mvu)
read_verilog -sv \
	{mvu_dir}/mvu_pkg.sv \
	{mvu_dir}/mvu_vvu_axi.sv \
	{mvu_dir}/replay_buffer.sv \
	{mvu_dir}/mvu_vvu_8sx9_dsp58.sv \
	{mvu_dir}/mvu.sv \
	{gen_dir}/add_multi.sv \
	{*}[glob {gen_dir}/comp_*.sv]

# Simulation sources
set simset [current_fileset -simset]
add_files -fileset $simset {gen_dir}/$tb.sv
set_property top $tb $simset
set_property xsim.simulate.runtime all $simset

# Defines for simulation-only features
set_property verilog_define {FINN_SIMULATION=1} $simset

# Run Simulation
launch_simulation
close_sim

quit
