stages:
  - sync
  - singularity_build
  - load_deps
  - test

variables:
  PIPELINE_NAME:
    description: "Optional name to better identify this pipeline"
    value: ""
  TEST_SUITE:
    description: "Select test suite to run"
    value: "full"
    options:
      - "none"
      - "quicktest"
      - "main"
      - "rtlsim"
      - "end2end"
      - "full"
  CPU_CORES:
    description: "Select number of CPU cores and test workers"
    value: "8"
  PARALLEL_JOBS:
    description: "Number of parallel Slurm array jobs per Benchmark job"
    value: "2"
  SLURM_TIMEOUT:
    description: "Select SLURM timeout"
    value: "3-0" # [days-hours]
  SLURM_PARTITION:
    description: "Slurm partition (e.g., normal, largemem, fpga, gpu)"
    value: "normal"
  SLURM_QOS:
    description: "Optional QoS option (include --qos, e.g., --qos express)"
    value: ""
  MANUAL_CFG_PATH:
    description: "Use this config file instead of configs stored in the repo. Path must be accessible to runner"
    value: ""
  FINN_XILINX_VERSION:
    value: "2022.2"
  SINGULARITY_IMG_SELECT:
    value: "finn_dev.sif"

workflow:
  name: '$PIPELINE_NAME'
  rules:
    # Run pipeline for GitHub PRs to dev (does not support PRs from forks)
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" && $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == "dev"
    # Run pipeline for pushes to dev
    - if: $CI_COMMIT_BRANCH == "dev"
    # Run pipeline if manually triggered via API or web GUI
    - if: $CI_PIPELINE_SOURCE == "api"
    - if: $CI_PIPELINE_SOURCE == "web"
    # Run pipeline if scheduled (only for nightly sync of finn-dev)
    - if: $CI_PIPELINE_SOURCE == "schedule"

Sync finn-dev:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: sync
  tags:
    # Run where full Docker + Singularity is available
    - image_build
  rules:
    # Only run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - mkdir -p ../github_clone && cd ../github_clone
    - rm -rf finn-plus # Ensure we do a fresh clone (TODO: better way to handle this on job level?)
    - git clone git@github.com:eki-project/finn-plus.git && cd finn-plus
    - git remote add upstream https://github.com/Xilinx/finn.git
    - git checkout finn-dev
    - git pull upstream dev
    - git push origin finn-dev

Singularity Image Build:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: singularity_build
  tags:
    # Run where full Docker + Singularity is available
    - image_build
  rules:
    # Do not run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    # Only run if relevant files changed relative to dev branch
    - changes:
        paths:
          - requirements.txt
          - docker/Dockerfile.finn
          - docker/finn_entrypoint.sh
          - docker/quicktest.sh
        compare_to: "dev"
  script:
    - docker build --no-cache -f docker/Dockerfile.finn --tag=finn_docker_export .
    - apptainer build --force finn_singularity_image.sif docker-daemon://finn_docker_export:latest
    - rsync -vh finn_singularity_image.sif $PATH_SINGULARITY_IMG_BUILD/finn-plus/finn_$CI_COMMIT_REF_SLUG.sif
  after_script: # Clean caches
    - echo 'y' | docker image prune
    - echo 'y' | docker builder prune
    - echo 'y' | apptainer cache clean

Fetch Repos:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: load_deps
  tags:
    - login
  rules:
    # Do not run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    # Otherwise run
    - when: always
  cache: 
    key: $CI_COMMIT_SHA
    paths:
      - deps
  script:
    - ./fetch-repos.sh

FINN Test Suite 2022.2:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: test
  rules:
    # Do not run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    # Do not run if test suite has been deselected
    - if: $TEST_SUITE == "none"
      when: never
    # Select different Singularity image if it deviates from default (dev branch)
    - changes:
        paths:
          - requirements.txt
          - docker/Dockerfile.finn
          - docker/finn_entrypoint.sh
          - docker/quicktest.sh
        compare_to: "dev"
      variables:
        SINGULARITY_IMG_SELECT: "finn_$CI_COMMIT_REF_SLUG.sif"
    # Always run, as long as there was no prior failure
    - when: on_success
  cache: 
    key: $CI_COMMIT_SHA
    policy: pull
    paths:
      - deps
  variables:
    SCHEDULER_PARAMETERS: "-A $PROJECT_ACCOUNT -p $SLURM_PARTITION -t $SLURM_TIMEOUT $SLURM_QOS --nodes 1 --ntasks 1 --cpus-per-task $CPU_CORES --exclusive"
    PYTEST_PARALLEL: "$CPU_CORES"
    FINN_SINGULARITY: "$PATH_SINGULARITY_IMG/finn-plus/$SINGULARITY_IMG_SELECT"
    FINN_XILINX_VERSION: "2022.2"
  before_script:
    - cp -dfR .. $PATH_WORKDIR # Copy to working directory (e.g. RAMdisk)
    - cd $PATH_WORKDIR/finn-plus
    - module load system singularity
  script:
    - ./run-docker.sh quicktest.sh $TEST_SUITE

FINN Test Suite 2024.1:
  extends: FINN Test Suite 2022.2
  variables:
    FINN_XILINX_VERSION: "2024.1"

Bench (Manual):
  stage: test
  rules:
    # Do not run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $MANUAL_CFG_PATH != ""
  trigger:
    include: benchmarking/bench-ci.yml
    strategy: depend
    forward:
      pipeline_variables: true
  variables:
    BENCH_CFG: "manual"

Bench:
  stage: test
  rules:
    # Do not run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $MANUAL_CFG_PATH == ""
  trigger:
    include: benchmarking/bench-ci.yml
    strategy: depend
    forward:
      pipeline_variables: true
  parallel:
    matrix:
      - BENCH_CFG: [mvau_test]

#dev: mvau_test
#fifo: fifosizing_test, metafi_fifosizing_test, resnet50_fifosizing_test
#transformer: transformer_test, transformer_radioml_all

#TODO: add selector for none, reduced, full benchmark suite

#TODO: introduce result collect job on parent level for easier visualization/excel interfacing
#TODO: more control via (optional) variables
#TODO: move power measurement from polling-based script to its own job/runner
#TODO: ensure a freshly initialized workdir on job/runner level (e.g. created directories seem to stay there)
#TODO: (optionally) save ALL build artifacts/logs/temporary files to artifacts or PFS for debugging (maybe via Jacamar feature of setting individual persistent workdirs?)
#TODO: fix clock frequency discrepancies between setting, synth, and driver