# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause

import numpy as np
import os
import shutil
from qonnx.core.datatype import DataType

from finn.custom_op.fpgadataflow.pwpolyf import PWPolyF
from finn.custom_op.fpgadataflow.rtlbackend import RTLBackend
from finn.util.data_packing import array2hexstring
from finn.util.torch_hw_modules import (
    CLAMP_CFG,
    NUM_OCTAVES,
    SUPPORTED_FUNCS,
    _fit_coefficients,
)


def _float_to_hex(f):
    """Convert a Python float to a 32-bit IEEE 754 hex string."""
    return array2hexstring(np.array([f]), DataType["FLOAT32"], 32, prefix="").upper()


def _generate_coeffs_pkg_data(K, degree=2, num_samples=1000):
    """Generate the pwpolyf_pkg.sv package content for a given K value.

    Produces a SystemVerilog package with a func_cfg_t struct per activation
    function, containing clamping parameters and polynomial coefficients.
    """
    num_subs = 1 << K
    num_segs = 1 + 2 * NUM_OCTAVES * num_subs

    lines = []
    lines.append("// Auto-generated by pwpolyf_rtl.py - do not edit manually.")
    lines.append(
        "// DEGREE=%d K=%d NUM_OCTAVES=%d  Segments: %d" % (degree, K, NUM_OCTAVES, num_segs)
    )
    lines.append("")
    lines.append("package pwpolyf_pkg;")
    lines.append("")
    lines.append("    localparam int unsigned  DEGREE      = %d;" % degree)
    lines.append("    localparam int unsigned  K           = %d;" % K)
    lines.append("    localparam int unsigned  NUM_OCTAVES = %d;" % NUM_OCTAVES)
    lines.append("    localparam int unsigned  NUM_SEGS    = %d;" % num_segs)
    lines.append("")
    lines.append("    typedef struct {")
    lines.append("        int unsigned  neg_clamp;")
    lines.append("        int unsigned  pos_clamp;")
    lines.append("        bit           pos_passthrough;")
    lines.append("        int unsigned  coeffs[NUM_SEGS][DEGREE+1];")
    lines.append("    } func_cfg_t;")

    for func_name in SUPPORTED_FUNCS:
        cfg = CLAMP_CFG[func_name]
        coeffs = _fit_coefficients(func_name, K, degree=degree, num_samples=num_samples)
        label = func_name.upper()
        neg_hex = _float_to_hex(cfg["neg_clamp"])
        pos_hex = _float_to_hex(cfg["pos_clamp"])
        passthrough = 1 if cfg["pos_passthrough"] else 0

        lines.append("")
        lines.append("    localparam func_cfg_t  %s = '{" % label)
        lines.append("        neg_clamp:       32'h%s," % neg_hex)
        lines.append("        pos_clamp:       32'h%s," % pos_hex)
        lines.append("        pos_passthrough: %d," % passthrough)
        lines.append("        coeffs: '{")
        for seg in range(num_segs):
            coeff_strs = []
            for c in range(degree + 1):
                coeff_strs.append("32'h%s" % _float_to_hex(coeffs[seg, c]))
            comma = "," if seg < num_segs - 1 else ""
            lines.append("            '{ %s }%s\t// seg %d" % (", ".join(coeff_strs), comma, seg))
        lines.append("        }")
        lines.append("    };")

    lines.append("")
    lines.append("endpackage")
    lines.append("")
    return "\n".join(lines)


class PWPolyF_rtl(PWPolyF, RTLBackend):
    """RTL variant of PWPolyF, wraps the finn-rtllib pwpolyf IP."""

    def __init__(self, onnx_node, **kwargs):
        super().__init__(onnx_node, **kwargs)

    def get_nodeattr_types(self):
        my_attrs = {}
        my_attrs.update(PWPolyF.get_nodeattr_types(self))
        my_attrs.update(RTLBackend.get_nodeattr_types(self))
        return my_attrs

    def _generate_coeffs_pkg(self, num_samples=1000):
        K = self.get_nodeattr("K")
        degree = self.get_nodeattr("degree")
        return _generate_coeffs_pkg_data(K, degree=degree, num_samples=num_samples)

    def generate_hdl(self, model, fpgapart, clk):
        rtllib_dir = os.path.join(os.environ["FINN_ROOT"], "finn-rtllib/pwpolyf/hdl/")
        template_path = rtllib_dir + "pwpolyf_template_wrapper.v"
        code_gen_dir = self.get_nodeattr("code_gen_dir_ipgen")

        pe = self.get_nodeattr("PE")
        func = self.get_nodeattr("func")
        topname = self.get_verilog_top_module_name()

        self.set_nodeattr("gen_top_module", topname)

        code_gen_dict = {
            "$MODULE_NAME_AXI_WRAPPER$": topname,
            "$TOP_MODULE$": topname,
            "$PE$": str(pe),
            "$FUNC$": '"%s"' % func,
            "$IN_WIDTH$": str(pe * 32),
            "$OUT_WIDTH$": str(pe * 32),
        }

        # apply code generation to wrapper template
        with open(template_path, "r") as f:
            template = f.read()
        for key, value in code_gen_dict.items():
            template = template.replace(key, str(value))
        with open(os.path.join(code_gen_dir, topname + ".v"), "w") as f:
            f.write(template)

        # copy RTL source files
        for sv_file in ["pwpolyf.sv", "queue.sv"]:
            shutil.copy(rtllib_dir + sv_file, code_gen_dir)

        # generate package with coefficients matching the node's K and degree
        pkg_data = self._generate_coeffs_pkg()
        with open(os.path.join(code_gen_dir, "pwpolyf_pkg.sv"), "w") as f:
            f.write(pkg_data)

        self.set_nodeattr("ipgen_path", code_gen_dir)
        self.set_nodeattr("ip_path", code_gen_dir)

    def get_rtl_file_list(self, abspath=False):
        if abspath:
            code_gen_dir = self.get_nodeattr("code_gen_dir_ipgen") + "/"
            rtllib_dir = os.path.join(os.environ["FINN_ROOT"], "finn-rtllib/pwpolyf/hdl/")
        else:
            code_gen_dir = ""
            rtllib_dir = ""

        verilog_files = [
            code_gen_dir + "pwpolyf_pkg.sv",
            rtllib_dir + "pwpolyf.sv",
            rtllib_dir + "queue.sv",
            code_gen_dir + self.get_nodeattr("gen_top_module") + ".v",
        ]
        return verilog_files

    def execute_node(self, context, graph):
        mode = self.get_nodeattr("exec_mode")
        if mode == "cppsim":
            PWPolyF.execute_node(self, context, graph)
        elif mode == "rtlsim":
            RTLBackend.execute_node(self, context, graph)

    def code_generation_ipi(self):
        code_gen_dir = self.get_nodeattr("code_gen_dir_ipgen")

        sourcefiles = [
            "pwpolyf_pkg.sv",
            "pwpolyf.sv",
            "queue.sv",
        ]
        sourcefiles.append(self.get_nodeattr("gen_top_module") + ".v")
        sourcefiles = [os.path.join(code_gen_dir, f) for f in sourcefiles]

        cmd = []
        for f in sourcefiles:
            cmd += ["add_files -norecurse %s" % (f)]
        cmd += [
            "create_bd_cell -type module -reference %s %s"
            % (self.get_nodeattr("gen_top_module"), self.onnx_node.name)
        ]
        return cmd
