pipeline {
    agent any
    parameters {
        string(name: 'FINN_CI_BRANCH', defaultValue: '', description: 'FINN branch to build')
        string(name: 'VIVADO_PATH', defaultValue: '', description: 'Path to Vivado installation')
    }
    environment {
        DOCKER_TAG='finn_ci:$BUILD_ID'
        DOCKER_INST_NAME='finn_ci_$BUILD_ID'
        BUILD_PATH='/tmp/finn_ci_$BUILD_ID'
        VIVADO_IP_CACHE='$BUILD_PATH/vivado_ip_cache'
        DOCKER_CMD="python setup.py test --addopts '-k test_compilation_trafo'"
    }
    stages {
        stage("Clone") {
            steps {
                git branch: "${params.FINN_CI_BRANCH}", url: 'https://github.com/Xilinx/finn.git'
            }
        }
      stage('Build') {
            steps {
                sh """
                docker build -t $DOCKER_TAG -f docker/Dockerfile.finn_ci \
                --build-arg BUILD_PATH=$BUILD_PATH \
                --build-arg FINN_CI_BRANCH=${params.FINN_CI_BRANCH} \
                --build-arg VIVADO_PATH=${params.VIVADO_PATH} \
                docker/
                """
            }
        }
        stage('Test') {
            steps {
                sh """
                docker run --name $DOCKER_INST_NAME \
                --hostname $DOCKER_INST_NAME \
                -v ${params.VIVADO_PATH}:${params.VIVADO_PATH}:ro \
                -e VIVADO_PATH=${params.VIVADO_PATH} \
                -e FINN_INST_NAME=$DOCKER_INST_NAME \
                -e VIVADO_IP_CACHE="$VIVADO_IP_CACHE" \
                $DOCKER_TAG bash -c "$DOCKER_CMD"
                """
            }
        }
    }
}
