/****************************************************************************
 * Copyright Advanced Micro Devices, Inc.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * @brief	Coefficients and parameters for the softmaxf exp() polynomial.
 * @author	Shane Fleming <shane.fleming@amd.com>
 *
 * @description
 *	Package consolidating the piecewise polynomial approximation of exp(x)
 *	over the non-positive domain (-clamp_threshold, 0]. Used by the second
 *	pipeline stage of softmaxf, where every input has already had the per-
 *	vector maximum subtracted so that x <= 0.
 *
 *	Coefficient data auto-generated by softmaxf_coeffs.py -- DEGREE=2
 *	K=2 NUM_OCTAVES=4.  Segments: 17  Coefficients per
 *	segment: 3.
 *	Polynomial:  y = c[0] + c[1]*x + c[2]*x^2 + ... + c[d]*x^d
 *	Horner form: y = c[0] + x*(c[1] + x*(c[2] + ... x*c[d]))
 *
 *	Segment index encoding:
 *	  0                  = near-zero (|x| < 1.0)
 *	  1 .. NUM_SEGS-1    = negative octaves, octave-major + sub-minor
 *	                       octave o = |x| in [2^o, 2^(o+1)), exp_bits=127+o
 ***************************************************************************/

package softmaxf_pkg;

	localparam int unsigned  EXP_DEGREE      = 2;
	localparam int unsigned  EXP_K           = 2;
	localparam int unsigned  EXP_NUM_OCTAVES = 4;
	localparam int unsigned  EXP_NUM_SEGS    = 17;

	// |x| >= 2^NUM_OCTAVES => exp_bits >= EXP_CLAMP_EXP => result clamped to 0
	localparam logic [ 7:0]  EXP_CLAMP_EXP = 8'd131;
	localparam logic [31:0]  FP32_NEG_INF  = 32'hFF800000;

	function bit fp32_is_pos_inf(input logic [31:0] x);
		return  (x[31] == 1'b0) && (x[30:23] == 8'hFF) && (x[22:0] == '0);
	endfunction

	// Polynomial coefficients (Horner: c[0] + x*(c[1] + x*c[2] + ...)).
	localparam logic [31:0]  EXP_COEFFS[EXP_NUM_SEGS][EXP_DEGREE+1] = '{
		'{ 32'h3F7E975F, 32'h3F6E39C4, 32'h3E9E110F },	// [ 0] near_zero: [-1.0000, +0.0000]
		'{ 32'h3F6568E0, 32'h3F30D873, 32'h3E266868 },	// [ 1] neg_oct0_sub0: [-1.2500, -1.0000]
		'{ 32'h3F571F0B, 32'h3F19ED5F, 32'h3E01993B },	// [ 2] neg_oct0_sub1: [-1.5000, -1.2500]
		'{ 32'h3F471555, 32'h3F047EBE, 32'h3DC9DCE8 },	// [ 3] neg_oct0_sub2: [-1.7500, -1.5000]
		'{ 32'h3F36123F, 32'h3EE206A3, 32'h3D9D3604 },	// [ 4] neg_oct0_sub3: [-2.0000, -1.7500]
		'{ 32'h3F1CAD47, 32'h3EB04426, 32'h3D58D2EA },	// [ 5] neg_oct1_sub0: [-2.5000, -2.0000]
		'{ 32'h3EF79FAF, 32'h3E76B305, 32'h3D0382A5 },	// [ 6] neg_oct1_sub1: [-3.0000, -2.5000]
		'{ 32'h3EBE177C, 32'h3E29926B, 32'h3C9F87B4 },	// [ 7] neg_oct1_sub2: [-3.5000, -3.0000]
		'{ 32'h3E8E855F, 32'h3DE5E422, 32'h3C418511 },	// [ 8] neg_oct1_sub3: [-4.0000, -3.5000]
		'{ 32'h3E351B65, 32'h3D7F1912, 32'h3BB9492D },	// [ 9] neg_oct2_sub0: [-5.0000, -4.0000]
		'{ 32'h3DB86F15, 32'h3CDDC5A1, 32'h3B085362 },	// [10] neg_oct2_sub1: [-6.0000, -5.0000]
		'{ 32'h3D33A044, 32'h3C3C3F16, 32'h3A489B0F },	// [11] neg_oct2_sub2: [-7.0000, -6.0000]
		'{ 32'h3CA917FA, 32'h3B9CF423, 32'h399398F1 },	// [12] neg_oct2_sub3: [-8.0000, -7.0000]
		'{ 32'h3BDC0487, 32'h3AAE22EA, 32'h388AEAFF },	// [13] neg_oct3_sub0: [-10.0000, -8.0000]
		'{ 32'h3AAAF037, 32'h396222A8, 32'h3716676D },	// [14] neg_oct3_sub1: [-12.0000, -10.0000]
		'{ 32'h397B5E6D, 32'h380EC577, 32'h35A2D6FA },	// [15] neg_oct3_sub2: [-14.0000, -12.0000]
		'{ 32'h3831799C, 32'h36B09D2D, 32'h34304DC0 }	// [16] neg_oct3_sub3: [-16.0000, -14.0000]
	};

endpackage
