

ifndef XILINX_SDX
$(error Environment variable XILINX_SDX is required and should point to SDAccel install area)
endif


SDA_FLOW = cpu_emu
HOST_CFLAGS = $(DEF)
HOST_LFLAGS = 

KERNEL_SRCS = $(KERNEL_FILE)
KERNEL_NAME = $(KERNEL)
KERNEL_DEFS = $(DEF) 
KERNEL_INCS = $(INC) 
#set target device for XCLBIN
#XDEVICE=xilinx:xil-accel-rd-ku115:4ddr-xpr:4.0
XDEVICE=xilinx:aws-vu9p-f1:4ddr-xpr-2pr:4.0
KEEP_TEMP=1
KERNEL_DEBUG=
XCLBIN_NAME=../BlackBoxJam
HOST_CFLAGS+=-DTARGET_DEVICE=\"${XDEVICE}\"
#BOARD_SETUP_FILE needs to point to setup.sh generated by xbinst command
BOARD_SETUP_FILE=setup.sh
ifeq (${SDA_FLOW},cpu_emu)
    CLCC_OPT += -t sw_emu --xp prop:kernel.$(KERNEL).kernel_flags=$(DEF) $(INC)  
    XCLBIN = ${XCLBIN_NAME}_cpu_emu.xclbin
else ifeq (${SDA_FLOW},hw_emu)
    CLCC_OPT += -t hw_emu
    XCLBIN = ${XCLBIN_NAME}_hw_emu.xclbin
else ifeq (${SDA_FLOW},hw)
    XCLBIN = ${XCLBIN_NAME}_hw.xclbin
    CLCC_OPT += -t hw -O3 --max_memory_ports=all --xp prop:kernel.$(KERNEL).kernel_flags=$(DEF) $(INC) 
endif

HOST_ARGS = ${XCLBIN}

COMMON_DIR = ./
include ${COMMON_DIR}/common.mk

