# 'dr.bd.tcl' file generated by vpl 2024.1 throws an error when building
# Seems to be caused by the 2024.1 clock reset automation process being incompatible with the platform/kernels
# Replace the 'dr.bd.tcl' in vpl/.local generated by 2024.1 tools, with dr.bd.tcl generated by 2023.2 tools, before running the file
# Will build correctly and give the expected checksum when running instrumentation wrapper

file copy -force ../../../../../src/1x/dr.bd_1x.tcl ./.local/dr.bd.tcl
